-- Fix missing columns in schools table
ALTER TABLE schools ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS logoUrl TEXT;
